_BASE_: ../maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml
DATALOADER:
  NUM_WORKERS: 4
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 2
  SEM_SEG_HEAD:
    NUM_CLASSES: 2
  RETINANET:
    NUM_CLASSES: 2
  MaskDINO:
    TEST:
      INSTANCE_ON: true
      PANOPTIC_ON: false
      SEMANTIC_ON: false
      SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: true
SOLVER:
  MAX_ITER: 150000
  STEPS: (50000, 90000, 130000)
  CHECKPOINT_PERIOD: 5000
DATASETS:
  TRAIN: ("asparagus_full_1920_train",)
  TEST: ("asparagus_full_1920_val",)
TEST:
  EVAL_PERIOD: 5000 # default 5000
SOLVER:
  CHECKPOINT_PERIOD: 5000
SEED: 11631026