_BASE_: ../swin/maskdino_swin_base.yaml
DATALOADER:
  NUM_WORKERS: 4
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 2
  SEM_SEG_HEAD:
    NUM_CLASSES: 2
  RETINANET:
    NUM_CLASSES: 2
  MaskDINO:
    TEST:
      INSTANCE_ON: true
      PANOPTIC_ON: false
      SEMANTIC_ON: false
SOLVER:
  MAX_ITER: 150000
  STEPS: (120000,)
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 1
DATASETS:
  TRAIN: ("20231213_ValidationSet_0point1_train",)
  TEST: ("20231213_ValidationSet_0point1_val",)
TEST:
  EVAL_PERIOD: 10000
SEED: 11631026