_BASE_: ../maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 2
  SEM_SEG_HEAD:
    NUM_CLASSES: 2
  RETINANET:
    NUM_CLASSES: 2
SOLVER:
  MAX_ITER: 50000
  STEPS: (30000, 40000)
  CHECKPOINT_PERIOD: 5000
DATASETS:
  TRAIN: ("asparagus_train",)
  TEST: ("asparagus_val",)
TEST:
  EVAL_PERIOD: 0 # default 5000